### ISSUE TITLE
Out of bounds error and import error

### ISSUE THREAD

**Issue by Jenifer-Anjali** [delmalih/mias-mammography-obj-detection#2]
hey, i tried implementing the faster-r-cnn code for reference purpose in windows but when i try to Generate COCO or VOC augmented data code, i get index out of bounds error at line  68 to 75 in generate_COCO_annotations.py and also that i get import error as "no module maskrcnn_benchmark found" while i try to implement train.py even though i tried correcting the path.

Can you please help me solve the issue? Thankyou

Also i have attached the images for your reference.

     
![1](https://user-images.githubusercontent.com/49978353/76340196-2ee43600-6321-11ea-84d2-c4d9c7e0cb20.PNG)
![2](https://user-images.githubusercontent.com/49978353/76340207-3572ad80-6321-11ea-9be9-56bcafa27b51.PNG)

**Comment by delmalih** [comment]
Hey,

For the 1st issue, could you please show me your Info.txt file ? (It should normally be a copy/paste of the positions of tumors given here : http://peipa.essex.ac.uk/info/mias.html - starting from `mdb001 G CIRC B 535 425 197` ...)

For the 2nd issue, make sure that the package maskrcnn_benchmark is correctly installed : https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/INSTALL.md#windows-10

**Comment by Jenifer-Anjali** [comment]
Thank you

**Comment by Jenifer-Anjali** [comment]
Hello,
As you mentioned i edited the info.txt file and tried to run the generate_COCO_annotations.py file but i get this key error. I have attached the info.txt file and the snapshots of the error.  Also i have included the directory structure of the code, kindly help me solve this problem. 
![3](https://user-images.githubusercontent.com/49978353/76380413-b27d4180-6378-11ea-8199-adb662a2819a.PNG)
![4](https://user-images.githubusercontent.com/49978353/76380424-b7da8c00-6378-11ea-990b-4656d92ce0c3.PNG)
![5](https://user-images.githubusercontent.com/49978353/76380432-bdd06d00-6378-11ea-939a-51525fe7ddc2.PNG)
[Info.txt](https://github.com/delmalih/MIAS-mammography-obj-detection/files/4315942/Info.txt)

**Comment by delmalih** [comment]
Here is the correct Info.txt file you should use : https://github.com/delmalih/MIAS-mammography-obj-detection/blob/master/utils/Info.txt

**Comment by Jenifer-Anjali** [comment]
Hello sir,
This is the file i have used already but still i'm getting "index 0 is out of bounds  for axis 0 with size 0" when i try to map it. Exactly at line no 134 in generate_COCO_annotations.py and similar code of lines. I also tried removing the headers but the again i get error REFNUM and so on.  I guess its because Info.txt file can't be read. Also could you please look at my directory structure and correct me if something's wrong.

### 2. Generate COCO or VOC augmented data
When i tried to run this command i get Info.txt is not found
python generate_COCO_annotations.py --images ../mias-db/ --annotations ../mias-db/Info.txt --output ../mias-db/COCO--aug_fact 20 --train_val_split 0.9 

![1](https://user-images.githubusercontent.com/49978353/76451206-180f1380-63f5-11ea-8575-5b9bb2c2707b.PNG)

![2](https://user-images.githubusercontent.com/49978353/76451210-1a716d80-63f5-11ea-850f-8083e5efbbd7.PNG)

![3](https://user-images.githubusercontent.com/49978353/76451213-1c3b3100-63f5-11ea-86aa-495906bd74de.PNG)

![4](https://user-images.githubusercontent.com/49978353/76452350-03337f80-63f7-11ea-968f-3e566343a209.PNG)

**Comment by delmalih** [comment]
Okay let me check and get back to you later,

Best

Le mer. 11 mars 2020 à 19:35, Jenifer_zayn <notifications@github.com> a
écrit :

**Comment by Jenifer-Anjali** [comment]
Okay thank you very much sir

**Comment by delmalih** [comment]
It works fine for me. Make sure :
- You run it with python3.6
- You have installed all packages that are in the requirements.txt
And try to run this command : 
```python generate_COCO_annotations.py -i ./mias-db -a ./utils/Info.txt -o ../mias-db/COCO --aug_fact 20 --train_val_split 0.9```

**Comment by Jenifer-Anjali** [comment]
Oh I used python 3.7 let me try this and let you know how it goes.



Thanks

**Comment by picEmily** [comment]
@Jenifer-Anjali  
in windows system，at line num 67 in generate_COCO_annotations.py should be changed as this：
img_name,_ = os.path.splitext(os.path.basename(img_path))

**Comment by Jenifer-Anjali** [comment]
> @Jenifer-Anjali
> in windows system，at line num 67 in generate_COCO_annotations.py should be changed as this：
> img_name,_ = os.path.splitext(os.path.basename(img_path))

Thank you.
