### ISSUE TITLE
Retinanet model running error

### ISSUE THREAD

**Issue by bovane** [delmalih/mias-mammography-obj-detection#3]
Hello,I am a student. I have some doubt about running retinanet model . when I use google colab run retinanet model I couldn't understand the parameters meaning，could you explain for me  and help me run correctly ？
<img width="1150" alt="截屏2020-04-10 下午11 26 39" src="https://user-images.githubusercontent.com/40169572/79002653-7dd0f580-7b83-11ea-8263-c5aa08437c78.png">
By the way, I can execute the faster-rcnn model correctly ! Thank you

**Comment by bovane** [comment]
@delmalih

**Comment by delmalih** [comment]
Hello, your issue comes from the way you run the command with colab. Try running the command using one line.

Also, make sure to replace all parameters "<...>" with your own. For example : <Batch size> should be replaced by the batch size you want.

**Comment by bovane** [comment]
thank you ,but I can't find the file such as config-file,could you explain it to me ? 
<img width="1185" alt="截屏2020-04-11 上午12 29 10" src="https://user-images.githubusercontent.com/40169572/79006432-b83e9080-7b8b-11ea-9fde-c337f237eb22.png">
@delmalih

**Comment by bovane** [comment]
I just download these code and run it with colab , these peramters such as config-file and model.weight I can't find them. So I can't run these command correctly . Could you help me ? I'm stuck for a long time
I‘m a fresh-bird，alway stupied.
<img width="1185" alt="截屏2020-04-11 上午12 29 10" src="https://user-images.githubusercontent.com/40169572/79007189-3e0f0b80-7b8d-11ea-9e46-905af4c9b07b.png">

Such as for this command, I can't find the config-file ! Are they in your program ?
@delmalih

**Comment by delmalih** [comment]
If you're trying tu run an inference for he faster r-cnn, for the modeil weights, either you train on your own dataset or you can download some pretrained models on the model zoo : https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/MODEL_ZOO.md

For the config file check here : https://github.com/facebookresearch/maskrcnn-benchmark/tree/master/configs
There is plenty of them, try to create your own file or copy/paste an existing one

**Comment by bovane** [comment]
Thank you very much ，I will try it again ! Thank you !

**Comment by bovane** [comment]
With your help I succeed in training and runing an inference,Thank you ☺️ ,but when I am trying to train the retinanet there are some problem.
<img width="717" alt="截屏2020-04-11 上午12 53 26" src="https://user-images.githubusercontent.com/40169572/79011452-a0203e80-7b96-11ea-80b7-2865bb968903.png">

train.py: error: argument dataset_type: invalid choice: ' --tensorboard-dir' tensorboard-dir  peramters and coco dataset error . I guess wehther I need download coco dataset .tar.gz file ? other than the path ?  Could you explain it for me ? Thank you !

**Comment by bovane** [comment]
@delmalih

**Comment by delmalih** [comment]
For the tensorboard-dir parameter, you need to give any folder to store some files required for the tensorboard (for ex. /tmp/tensorboard)
After the coco parameter, you need to give the path to your dataset (in the coco format !important!). Take a look at the MSCoco dataset to get this format.

**Comment by bovane** [comment]
Thank you very much for your help, I will keep trying

**Comment by bovane** [comment]
I'm Sorry for my stupied ! I konw I need to give to my dataset path with coco format ! but I just download the all-mias.tar.gz and use the generate_COCO_annotations.py to create the coco dataset ! 
<img width="1092" alt="截屏2020-04-11 上午2 09 51" src="https://user-images.githubusercontent.com/40169572/79012789-b5e33300-7b99-11ea-9fd6-7dc56838bf44.png">

then I use the coco path for peramter . I don't understand the dataset should be looklike !

**Comment by delmalih** [comment]
Ok so normally, you should set your dataset_path as "../mias-db/COCO" and it should work. The `generate_COCO_annotations.py` script creates a COCO like database with the MIAS dataset.

**Comment by bovane** [comment]
uh,so sad 😭 😔 😢 🙁  I can't run the retinanet correctly ! for coco dataset path I use absolutely path . 
<img width="1240" alt="截屏2020-04-11 上午2 32 51" src="https://user-images.githubusercontent.com/40169572/79014297-2e97be80-7b9d-11ea-9c50-d2385644ae4b.png">

**Comment by delmalih** [comment]
First, remove all "\", we use them only if we want to write commands on multiple lines.
Then, put your paths between quotation marks "/content/drive/...."

**Comment by bovane** [comment]
I have tried use the quotation marks my coco dataset pathway,but still fail

**Comment by delmalih** [comment]
Could you send me the entire command you used to run the training process ? Along with its output

**Comment by bovane** [comment]
ok,I will !
this is your model command line
!python train.py --compute-val-loss \ # Computer val loss or not
                --tensorboard-dir <Path to the tensorboard directory> \
                --batch-size <Batch size> \
                --epochs <Nb of epochs> \
                coco <Path to the COCO dataset>

then I use :
!python train.py --compute-val-loss \ # Computer val loss or not
                --tensorboard-dir output/ \
                --batch-size 20 \
                --epochs 10 \
                coco /content/drive/Shared drives/BoVane/mias-db/COCO

then it will occur the error  IndentationError: unexpected indent   !!!

when I use the single command line like this:
!python train.py --compute-val-loss \  --tensorboard-dir output/ \ --batch-size 20 \ --epochs 10 \ coco /content/drive/Shared drives/BoVane/mias-db/COCO


Using TensorFlow backend.
2020-04-10 18:49:44.153250: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
usage: train.py [-h]
                [--snapshot SNAPSHOT | --imagenet-weights | --weights WEIGHTS | --no-weights]
                [--backbone BACKBONE] [--batch-size BATCH_SIZE] [--gpu GPU]
                [--multi-gpu MULTI_GPU] [--multi-gpu-force] [--epochs EPOCHS]
                [--steps STEPS] [--lr LR] [--snapshot-path SNAPSHOT_PATH]
                [--tensorboard-dir TENSORBOARD_DIR] [--no-snapshots]
                [--no-evaluation] [--freeze-backbone] [--random-transform]
                [--image-min-side IMAGE_MIN_SIDE]
                [--image-max-side IMAGE_MAX_SIDE] [--config CONFIG]
                [--weighted-average] [--compute-val-loss] [--multiprocessing]
                [--workers WORKERS] [--max-queue-size MAX_QUEUE_SIZE]
                {coco,pascal,kitti,oid,csv} ...
train.py: error: argument dataset_type: invalid choice: ' ' (choose from 'coco', 'pascal', 'kitti', 'oid', 'csv')

**Comment by delmalih** [comment]
Try this command :

`!python train.py --compute-val-loss --tensorboard-dir "/tmp/tensorboard-dir" --batch-size 20 --epochs 10 coco "/content/drive/Shared drives/BoVane/mias-db/COCO"`

**Comment by bovane** [comment]
wow 🤩 😯 😲 !  I can run this command Thank you !
but there is another error ! 
Using TensorFlow backend.
2020-04-10 18:53:19.156283: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "train.py", line 511, in <module>
    main()
  File "train.py", line 440, in main
    keras.backend.tensorflow_backend.set_session(get_session())
  File "train.py", line 50, in get_session
    config = tf.ConfigProto()
AttributeError: module 'tensorflow' has no attribute 'ConfigProto'

I am just finding the train.py to fix the bug ! Thank you 🙏 😊 ☺️

**Comment by delmalih** [comment]
Check your tf version and make sure that it is compatible with the code

**Comment by bovane** [comment]
yep !  I really appreciate your help, now I only have fcos model left ！
